### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by jimparker** [dropax/betaflight-for-eachine-racer-250#1]
Thank you so much for putting this together for the Eachine racer 250. Is there any chance you can update this to reflect the newer release from the BorisB firmware?

Again, thank you for creating this firmware. It is a perfect pairing with the Eachine 250 .

**Comment by dropax** [comment]
Now that 2.3.4 has settled for a while and seems to be stable I'm thinking about it. May take some time though, mine is quite constained atm. ;)

**Comment by Hebrews12v2** [comment]
Thanks for your work on this Dropax. Love how well it works!

**Comment by jimparker** [comment]
Wow Dropax. That was fast. Thank you so much. Going to update now.
