### ISSUE TITLE
iBus - Eachine Racer 250 w/ Flysky i10 Transmitter 

### ISSUE THREAD

**Issue by jimparker** [dropax/betaflight-for-eachine-racer-250#2]
I am currently using this transmitter and 10 channel receiver via PPM input. I have access to Aux 1-4 and standard flight control. I am debating setup via the recently added iBus support in Cleanflight. I have not yet figured out how to wire the receiver to the Eachine via a serial port. Also not sure if this would be advantageous to bother figuring out. Any thoughts would be appreciated. 

On a side note I modified the Eachine Racer frame to allow 6045 bullnose props to fit. This turned out to not be a good idea. My Luminier 1800 35c batteries drained in about 4-5 minutes. Turns out the motors don't work well with that size props. Go figure ;). That said the sound level of the drone was really quiet and flight was very stable. I could hover at around 7-10% throttle. There was no punch out though. Starting to understand why people have multiple drones and different configurations suited much more for different things. The Eachine was/is my first non syma/hubsan drone of which I purchased them all. 
Rant complete.

**Comment by dropax** [comment]
I don't use serial rx, but the usual way is signal to rx-pin on flexiport and configure uart2 to use it. If your research doesn't help ask on rcgroups. ;)

**Comment by jimparker** [comment]
Any benefit to using serial. 

PS. - just ordered the falcon 250. Lost the Eachine in high wind and cannot find it. Any gps method to avoid this in the future.

**Comment by ksibinski** [comment]
it's digital transmission, should be better than ppm:
https://quadmeup.com/pwm-ppm-and-serial-rx-explained/

I used this guide and everything works as expected:
http://blog.marax.cz/2016/03/ibus-with-cc3d-and-cleanflightbetafligh.html

right now I've stock ESC and oneshot doesn't work, but I read somewhere that OneShot125 is exclusive to PPM (it don't work with PWM), is this true - if I flash my ESC with BLHeli will I be able to use OneShot with IBUS?

**Comment by dropax** [comment]
You will. Afaik this restriction only applies to openpilot.

**Comment by ksibinski** [comment]
thank you
