### ISSUE TITLE
Eachine racer 250 ESCs won't sync

### ISSUE THREAD

**Issue by radioflyboy** [dropax/betaflight-for-eachine-racer-250#3]
I have attempted several times to load the latest version of Betaflight onto my quad. Everything seems fine in the Cleanflight configurator, but the ESCs won't stop beeping, won't sync, and the motors won't turn on. I can get it to work with cleanflight. Any ideas on what the issue might be? do I need to flash my ESCs to blheli?

Thanks,

James

**Comment by dropax** [comment]
Your ESCs don't speak Oneshot125. Disable it in the GUI or copy the ESC related section from release notes to CLI and type save. ;)

**Comment by si618** [comment]
You could also try flashing them: https://youtu.be/bbO_dmRdCVo 
I wouldn't be game to try his solder free approach though!

**Comment by radioflyboy** [comment]
Thanks Dropax. I had entered that section in the CLI, but didn't know that I needed to type save for it to stick. 

Now I have the motors synced up and working when commanded by the configurator, but I can't get the quad to arm under RC control. All I get is a solid green LED on the flight controller. I have tried it with and without using an auxiliary switch to arm it and am having no luck either way. 

With Cleanflight installed I have a solid green LED when it is disarmed and it switches to a solid blue one when armed. 

Any ideas on what I'm doing wrong this time?

Thanks,

James

**Comment by dropax** [comment]
See betaflight wiki:
https://github.com/borisbstyle/betaflight/wiki/Frequently-Asked-Questions#why-wont-my-fc-board-arm-after-upgrading-the-firmware-

Acc calibrateted and board within max_angle_inclination?

**Comment by ksibinski** [comment]
I don't want to open separate topic as this is similar issue, I can't calibrate my ESC when using recommended setting "set motor_pwm_rate = 500", they calibrate just fine on 400 though

**Comment by dropax** [comment]
What is your max_throttle?

**Comment by ksibinski** [comment]
it's 2000, and you recommend 1950 - what's the difference isn't that just resolution but real max throttle is in the ESC config in bheli suite, I could be of course wrong, I'll check one more thing - I'll try the setting motor_pwm_rate to 480, I remember open pilot was using this value

**Comment by dropax** [comment]
At max_throttle = 2000 and 500 hz there is no more gap between signals, so the ESC sees an invalid input. That's why those values belong together and you shouldn't cherrypick one until you know the impact.  ;) 

480 Hz will work but may result in aliasing on motor output. 500 Hz is in sync with every second loop. You won't notice the 5% difference in resolution.

**Comment by ksibinski** [comment]
thanks for explanation, and for keeping this project alive - I'll modify my settings

**Comment by ksibinski** [comment]
ok one more question do you also recommend setting the rates you posted with older version (2.5.3)?
and what settings do you recommend after flashing stock ESC with blheli (XP-12A MULTI) and enabling oneshot

**Comment by dropax** [comment]
Rates are just a matter of taste, adjust to your liking. ;)
As I haven't flown the racer with BLHeli I can't recommend any settings for that.

**Comment by dropax** [comment]
Oneshot doesn't work in this build.  See #5.
