### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mancmanGER** [dropax/betaflight-for-eachine-racer-250#4]
Hello Dropax,

thanks for your work here.

Are you planning to upgrade as well to 2.7.0?

**Comment by dropax** [comment]
For sure, just flew it on a naze - best BF version ever. :-) 
Update will be ready in a few hours.

**Comment by mancmanGER** [comment]
Hello dropax,

thanks for the fast reply.

Looking forward to use betaflight.

I have not used betaflight before, coming from openlibre.
If I understood things correctly I only need to update the bin file using GCS and adjust the ESC seetings with this here:

feature -ONESHOT125
set min_throttle = 1070
set max_throttle = 1950
set min_command = 1000
set motor_pwm_rate = 500

Cause my eachine is still stock.

Is this correct?

Or do you have any additonal PID settings which needs to be fine tuned?
I am using Spektrum transmitter and receiver, do I need to do something special or just making sure the channels are correctly set I am using PWM.

Or would you recommend to change to PPM settings, which can be done.

Sorry for asking so much.

**Comment by dropax** [comment]
Don't forget to type "save" in CLI. ;) 
You will lose channel 1 on PWM but PWM-RX is the default setting. Use PPM if your RX is capable. 
The PIDs are betaflight defaults and sadly I can't offer a better set. 

Betaflight requires some reading to get started:
http://wikirotors.com/index.php?title=Eachine_Racer_250#BetaFlight
https://github.com/borisbstyle/betaflight/wiki
https://github.com/cleanflight/cleanflight/tree/master/docs

**Comment by mancmanGER** [comment]
I came from the wikirotor page..finding you here...

If I understood things correctly I dont need to apply the mixing custom CLI stuff, cause you have this implemented in your version correct?

**Comment by dropax** [comment]
Correct. Uploading the new release right now.;)

**Comment by mancmanGER** [comment]
Thanks for the upload.
I tried it but gave up at the end.
Spent now 5 hours on this and could not get it to work.
The Racer was always in 3D mode and I could not get the stabilized (attitude) mode to work which I had on Librepilot.

I used 

The new version does not have the modes, what you can find in the www.

Or I am too stupid.

**Comment by mancmanGER** [comment]
what I meant last night is that autolevel modes (Angle or Horizon) are missing if I choose LUX.

**Comment by dropax** [comment]
What looptime have you set?  
Luxfloat eats way more cpu cycles than rewrite, use that, theres little to no difference in flight between the two pidcontrollers. 
If your level modes are gone "set acc_hardware = auto" and check for cpu load with "status".

**Comment by ksibinski** [comment]
hey dropax, thank you for new version!

I also have another question - you said you include motors mix - does it also include length measurements from motor to motor (like here https://www.iforce2d.net/mixercalc/) for ER250 or is just just general motor order mix set up for open pilot boards? 

also wanted to ask about pid controllers - I know luxfloat is too complex for F1 boards, but my ER250 fly a lot better with luxfloat on default pids (slightly modified now), on rewrite I've really a big problem tuning my ER250 PIDs to something usable

**Comment by dropax** [comment]
Technically speaking the mix is still the default QuadX, this build has the motor outputs "rewired in software" - the outcome in respect to flight behaviour is the same but has the advantage of motors matching the sliders in configurator and traces in blackbox logs. 

The only purpose of a geometry based custom mix is to get same PIDs for pitch and roll but as long as weight distribution is so different on these axis (centered on roll and spead out on pitch) you end up with different PIDs anyways. 
For a rectangular motor layout there is absolutely no sense in a custom mix and leaving it default saves some processing time. 

Luxfloat is fine for 1000 looptime even with acc enabled. It may be too much for lower looptimes, haven't tried. ;) 
Check CPU load with "status" if you want to set lower looptimes, it should be below 30-40%.

Btw. 250 lt is possible now with rewrite and acc. :D

**Comment by ksibinski** [comment]
yup that's what I wanted to minimize time spending tuning and being able to raise both roll and pitch together, but well as you said weight is still a factor and pids will differ anyway, so I'll just save some time not doing that motor mix.

yay I'll try lower looptimes, last time I checked 2000 I could only fly in acro mode (due to acc disabled to save cpu) and I still need some autoleveling, again thank you for sharing your knowledge - do you have any forum for discussion maybe or at least topic on RCG for dropax version of BF?

**Comment by dropax** [comment]
No specific forum on rcg, my contributions are spread out in the racer and falcon threads....
