### ISSUE TITLE
Only 2 motors work

### ISSUE THREAD

**Issue by Shagooo** [dropax/betaflight-for-eachine-racer-250#5]
Hi, i just flashed my CC3D with the latest firmware. Everything went smooth.
But i cannot get two of motors to spin. (1 & 2)
3 & 4 works correctly, but 1 & 2 doesn't spin at all.
When i try to calibrate the ESCs they (1 & 2) get no signal.

I have changed my ESCs from the stock once, so i can run oneshot125. (worked in LibrePilot)
I am also using SBUS, everything works in the reciever tab.
I can read the ESCs info from BLhelisuit (Cleanflight passthru) for all ESCs, and nothing seemse out of the ordinary.

**Comment by Shagooo** [comment]
Disabling Oneshot solved the problem. But why does two motors work with oneshot and two doesnt even spin? Is there some other setting that could cause this issue?

**Comment by dropax** [comment]
Racer or Falcon, which ESCs?  I had some reports of this issue for the Falcon, none for the racer but stock ESCs are non-oneshot so it won't occur. 
Please try same version of stock betaflight with "mixer QuadX1234". 
I don't think any settings will affect this, seems to be a timer issue but I can't spot anything in the code.

**Comment by dropax** [comment]
Please try the attached testbuild (rename from .txt to .bin). Does oneshot work with it and is motor order still matching CFC?

btw. feature SERVO_TILT would affect outputs but I assume you don't use it...

Edit: remove testbuild, motor order wrong

**Comment by ikirt** [comment]
I have noticed the same(on the Eachine Racer 250). After updating the ESC firmware to support OneShot only motors 3 and 4 work.
I just tried your testbuild above and all motors work but not in order.
testing from Motors TAB in CleanFlight:
Motor 1  moves 3
Motor 2  moves 2
Motor 3  moves 4
Motor 4 moves 1

**Comment by Shagooo** [comment]
Thanks for the test build, i will try it out when i get a chance (lots of work right now).
I have no SERVO_TILT. 

FUI: I have the DYS XM20A (V1)  ESCs

**Comment by dropax** [comment]
Thanks for testing and feedback. No need to test this @Shagooo. Just to be clear @ikirt: with all the motor numbers you named - are you referring to cleanflight motor count or the openpilot layout? 

Sorry Guys, after digging through the code for hours it seems I can't fix this (at least for the time being). 
Use stock betaflight - **either** with mixer QuadX1234 and live with "wrong" motors spinning in CFC **or** swap the signal wires in hardware.

**Comment by ikirt** [comment]
@dropax, yes I am using Cleanflight motor count. I have reverted back to 2.7.1 without OneShot and all motors are correct.

**Comment by dropax** [comment]
You will achieve noticable better flight behaviour and easier tuning with oneshot enabled. That's why I suggested to use it and give a s**t about the mismatch in motors tab, thats only kind of cosmetic. You want to fly and not only spin motors from CFC. :-D
Just visualize the openpilot layout (counting clockwise from top left motor) while you work in CFC. ;-)

**Comment by ksibinski** [comment]
sorry guys I just lost it here, when I flash stock betaflight for CC3D will I be able to even flight with wrong motor order?

**Comment by ksibinski** [comment]
just read it again from beginning to the end, so should "mixer QuadX1234" cli command be enough to make it work on ER250?

**Comment by si618** [comment]
Greetings, I also hit the issue with motors 1 & 2 not spinning with oneshot enabled on my racer. Tried dropax versions of betaflight 2.7.1 and 2.6.1. Both are working fine with oneshot disabled. Calibrated ESCs after enabling/disabling oneshot.

FWIW, also had motor 4 twitching on and off after oneshot was enabled. Guess that's why they say props off and battery out :)

Running littlebees 20a, blheli 14.5, damping light, medium motor timing. Not that it probably matters, but motors are DYS 2204 2300kv.

Happy to guinea pig betas if needed.

**Comment by si618** [comment]
Of course if I read the whole thread before posting, I would've seen the test build!

Flashed the test firmware in LibrePilot GSC, restored my 2.7.1 betaflight config, motors 3 & 4 started oscillating? with oneshot disabled. Not sure if oscillating is the right terminology, but they appeared to be alternating between rotating clockwise and anticlockwise. Might have just been one direction and my eyes deceiving me as the props slowed down...

Anyway, enabled oneshot, ESCs recalibrated, and it was looking better with props off on the bench, as all 4 motors started up. Alas, once I put the props on and fired up my racer in the lounge room, she flipped hard to the right on takeoff. Sorry carpet :)  So reverted back to 2.7.1 and oneshot disabled, which is working fine.

**Comment by dropax** [comment]
@skibinski: yes, just mixer QuadX1234
@si618: sorry for your carpet, but that was expectable after ikrit's test results - wrong motor order leads to desaster with the default mixer. Use normal BF and the mixer with oneshot, it is totally worth to trade flying oneshot for a little discomfort in motors tab and one line in CLI. ;-)

**Comment by si618** [comment]
No worries, will give it a go.

**Comment by dropax** [comment]
I'm confident it will work. 
If you still have the twitching issue lower min_command to 950 after calibration.

**Comment by dropax** [comment]
Closed
