### ISSUE TITLE
Stabilized modes produces a lot of heading

### ISSUE THREAD

**Issue by MarcosRZ** [dropax/betaflight-for-eachine-racer-250#6]
There's something wrong with stabilized modes. I have a terrible amount of vibration / heading all the time. ESC calibration, PIDs (using default ones) and other stuff might be OK since I get a flawless flight in non-stabilized modes such as Acro. When I was flying OpenPilot, stabilization worked perfectly, so there's not a HW issue, I think.

Check [this video](https://www.youtube.com/watch?v=tYG-e04erlc) to have an idea of what I'm talking about.

Edit: Forgot to mention that this is the CC3D version of Eachine Racer 250. More info can be found at the video description.

**Comment by dropax** [comment]
Late and you may found out by now, anyhow: reduce level strength (level p)
