### ISSUE TITLE
Eachine Falcon 250 pro F3

### ISSUE THREAD

**Issue by Brisingrox** [dropax/betaflight-for-eachine-racer-250#7]
I don't know if this the right place to ask for help but i gone try.

I've bought a Eachine Falcon 250 pro SPracing F3 and it comes with cleanflight 1.12 out of the box. I did upgrade to Betaflight 3.1.5 and it was a mess. since that point i did search all over the web for a solution but i did not find one? is someone here who could give me some advice how i could pass under betaflight and make my Falcon 250 pro flyable?

Thanks

**Comment by dropax** [comment]
This is indeed the wrong place to ask. Search on rcgroups.com ;)
